"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
const db=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
export default function Market(){
const [items,setItems]=useState([]),[session,setSession]=useState(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[msg,setMsg]=useState("");
async function load(){const x=await db.auth.getSession();setSession(x.data.session);const r=await db.from("research_opportunities").select("*").order("source_date",{ascending:false});setItems(r.data||[]);if(r.error)setMsg("Market data could not load: "+r.error.message)}
useEffect(()=>{load();const x=db.auth.onAuthStateChange(()=>load());return()=>x.data.subscription.unsubscribe()},[]);
async function enter(kind){setMsg("");const r=kind==="signup"?await db.auth.signUp({email,password}):await db.auth.signInWithPassword({email,password});setMsg(r.error?r.error.message:kind==="signup"?"Check your email to confirm your account.":"Signed in.")}
return <main className="memberMarket"><div className="marketHeader"><a href="/">AVE <span>AFRICAN VESSEL EXCHANGE</span></a>{session?<button onClick={()=>db.auth.signOut()}>Sign out</button>:<a href="#access">Member access</a>}</div><section className="marketHero"><p>AVE PRIVATE MARKET</p><h1>Curated maritime <em>opportunities.</em></h1><span>Public-source intelligence, confirmed opportunities and verified mandates are clearly distinguished.</span></section>{!session&&<section id="access" className="accessPanel"><div><p>MEMBER ACCESS</p><h2>Unlock the wider AVE market.</h2><span>Create a free account to access member inventory and register acquisition requirements.</span></div><form onSubmit={e=>e.preventDefault()}><input type="email" placeholder="Work email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} minLength="6" required/><button onClick={()=>enter("signup")}>Create account</button><button className="secondary" onClick={()=>enter("signin")}>Sign in</button>{msg&&<small>{msg}</small>}</form></section>}<section className="marketCatalogue"><div className="catalogueHead"><p>{session?"MEMBER INVENTORY":"PUBLIC PREVIEW"}</p><h2>{items.length} opportunities</h2></div><div className="catalogueGrid">{items.map(x=><article key={x.id}><div className="catMeta"><span>{x.ave_reference}</span><b>{x.research_status==="discovered"?"PUBLIC SOURCE":"AVE CONFIRMED"}</b></div><h3>{x.title}</h3><p>{x.specs}</p><div className="catFoot"><span>{x.market||x.country||"International"}</span><a href={x.source_url} target="_blank" rel="noreferrer">Source ↗</a></div></article>)}</div>{!session&&<div className="lockedMarket"><b>PRIVATE INVENTORY</b><h3>More opportunities are available to AVE members.</h3><a href="#access">Create member account →</a></div>}</section></main>}