"use client";
import {useMemo,useState} from "react";
import {createClient} from "@supabase/supabase-js";
const seed=[
{id:"AVE-L001",title:"DP2 AHTS — 151T Bollard Pull",type:"Anchor Handling Tug Supply",market:"Nigeria",status:"Public listing",price:"Rate on request",currency:"USD / NGN",commercial:"Charter",img:"https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?auto=format&fit=crop&w=1200&q=80",note:"Publicly advertised 22 Jun 2026 as available for charter in Nigeria. 151T bollard pull / DP2. AVE has not yet verified owner authority or current availability.",source:"VA Group",sourceUrl:"https://vog-atlas.com/vessel-news/"},
{id:"AVE-L002",title:"DP2 AHTS — 200T Bollard Pull",type:"Anchor Handling Tug Supply",market:"West Africa",status:"Public listing",price:"Price on request",currency:"USD",commercial:"For Sale",img:"https://images.unsplash.com/photo-1494412519320-aa613dfb7738?auto=format&fit=crop&w=1200&q=80",note:"Advertised 2 Apr 2026. Built 2012; 74.5m LOA; 2,542T DWT; 16,000 BHP; ABS class. AVE has not yet verified current availability.",source:"Sher Worldwide",sourceUrl:"https://sher-worldwide.com/product/3317-2012-built-16000bhp-dp2-aht-supply-vessel/"},
{id:"AVE-L003",title:"PSV DP2 — Sale or Charter",type:"Platform Supply Vessel",market:"International / West Africa enquiry",status:"Public listing",price:"Price on request",currency:"USD",commercial:"Sale / Charter",img:"https://images.unsplash.com/photo-1530053969600-caed2596d242?auto=format&fit=crop&w=1200&q=80",note:"Publicly advertised: built 2010, active condition, DP2, FiFi 1 and 680m² clear deck area. Location and availability require AVE verification.",source:"VA Group",sourceUrl:"https://vog-atlas.com/ships-for-sale-or-charter/"},
{id:"AVE-L004",title:"ASD Tug — 70T+ Bollard Pull",type:"ASD Tug",market:"West Africa",status:"Public listing",price:"Price on request",currency:"USD",commercial:"Charter / Towage",img:"https://images.unsplash.com/photo-1494412651409-8963ce7935a7?auto=format&fit=crop&w=1200&q=80",note:"Publicly advertised for charter/towage with last reported position in West Africa on 26 Jan 2026. >70T bollard pull. Current position requires verification.",source:"VA Group",sourceUrl:"https://vog-atlas.com/ships-for-sale-or-charter/"},
{id:"AVE-L005",title:"AHT — 80T Bollard Pull",type:"Anchor Handling Tug",market:"International / Africa delivery enquiry",status:"Public listing",price:"Price on request",currency:"USD",commercial:"For Sale",img:"https://images.unsplash.com/photo-1566847438217-76e82d383f84?auto=format&fit=crop&w=1200&q=80",note:"Publicly advertised: built 2005, active condition, IACS class, 80T bollard pull. AVE has not yet verified current location or availability.",source:"VA Group",sourceUrl:"https://vog-atlas.com/ships-for-sale-or-charter/"},
{id:"AVE-R006",title:"50T AHTS / Line Handling Requirement",type:"AHTS / Line Handling",market:"Brass Terminal, Bayelsa, Nigeria",status:"Buyer requirement",price:"US$4,500/day bareboat · US$6,000/day time charter",currency:"USD",commercial:"Charter Requirement",img:"https://images.unsplash.com/photo-1518465058-68b098b6b6d3?auto=format&fit=crop&w=1200&q=80",note:"Public request dated 4 Feb 2026 for crude-oil offtake support: 50T BP or closest, 2000+ build, IACS class, FiFi-1 and ≥150m² deck. AVE is not the mandate holder; requirement should be reconfirmed before nomination.",source:"Asian Dragon International",sourceUrl:"https://www.asiandragonintl.com/inventory.aspx?Action=Invent&Ident=181503"},
{id:"AVE-R007",title:"DP1 Work/Deck Vessel + Tug Requirement",type:"DP1 PSV / MPSV + Tug",market:"Cameroon — PDK/LIMA block",status:"Buyer requirement",price:"Quote requested",currency:"USD",commercial:"6-month Charter",img:"https://images.unsplash.com/photo-1540946485063-a40da27545f8?auto=format&fit=crop&w=1200&q=80",note:"Public request posted 27 Jul 2026 for Nov 2026 delivery: 6-month offshore workover support, 60–90m vessel range depending option, plus 3,000–4,000 HP tug. OVID vetting requested.",source:"ShipSelector",sourceUrl:"https://shipselector.com/requests/offshore-vessels/crane-barge/4682-dp1-workdeck-cargo-vessel-tug-for-6-month-charter-cameroon-nov-2026"},
{id:"AVE-L008",title:"12,000 HP AHTS — 140T BP",type:"Anchor Handling Tug Supply",market:"International / Africa enquiry",status:"Public listing",price:"Price on request",currency:"USD",commercial:"For Sale",img:"https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80",note:"Publicly advertised Sep 2026: built 2010, 70m LOA, 500m² deck, 2,040 DWT, DPS-1 and 140T bollard pull. Location and availability require AVE verification.",source:"VED Shipping",sourceUrl:"https://vedshipping.com/sale-and-purchase/vessels/ahtahtsahtsv/"}
]use client";
import {useMemo,useState} from "react";
import {createClient} from "@supabase/supabase-js";
const seed=[
{id:"AVE-L001",title:"50-Ton Bollard Pull Tug — Sale or Charter",type:"Tug Boat",market:"Port Harcourt, Nigeria",status:"Public listing",price:"US$2,000,000 sale · US$6,000/day charter",currency:"USD",commercial:"Sale / Charter",img:"https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?auto=format&fit=crop&w=1200&q=80",note:"Publicly advertised 9 Sep 2026 by Abenego Global. 50T bollard pull. Availability, ownership and terms require AVE verification.",source:"Abenego Global"},
{id:"AVE-L002",title:"DP2 AHTS — 151T Bollard Pull",type:"Anchor Handling Tug Supply",market:"Nigeria",status:"Public listing",price:"US$16,000,000 negotiable",currency:"USD",commercial:"For Sale",img:"https://images.unsplash.com/photo-1494412519320-aa613dfb7738?auto=format&fit=crop&w=1200&q=80",note:"Publicly advertised in 2026. Built 2013, DP2, FiFi Class 1, 75m LOA, 510m² deck. Availability and seller authority require AVE verification.",source:"African Land"},
{id:"AVE-L003",title:"DP2 Anchor Handling Tug — Charter",type:"AHTS / Offshore Support",market:"Port Harcourt, Nigeria",status:"Public listing",price:"₦16,200,000 advertised",currency:"NGN",commercial:"Charter",img:"https://images.unsplash.com/photo-1530053969600-caed2596d242?auto=format&fit=crop&w=1200&q=80",note:"Public listing updated 5 Jun 2026. Advertised as 148–157T bollard pull, 12,240 BHP, DP2, 25-person accommodation. Terms require AVE verification.",source:"Opor.ng"},
{id:"AVE-L004",title:"Offshore Tug / Supply Vessel — Charter",type:"Offshore Tug / Supply",market:"Port Harcourt, Nigeria",status:"Public listing",price:"Rate on request",currency:"USD / NGN",commercial:"Charter / Hire",img:"https://images.unsplash.com/photo-1494412651409-8963ce7935a7?auto=format&fit=crop&w=1200&q=80",note:"Publicly advertised: Nigerian flag, 2,137 GT, 2,918t DWT, 120MT bollard pull, 74.37m LOA, built 2000. Availability requires AVE verification.",source:"Baysal Group"},
{id:"AVE-L005",title:"65m DP2 AHTS Resale — 90T BP",type:"Anchor Handling Support Vessel",market:"International / Africa delivery",status:"Public listing",price:"Price on request",currency:"USD",commercial:"For Sale",img:"https://images.unsplash.com/photo-1566847438217-76e82d383f84?auto=format&fit=crop&w=1200&q=80",note:"Publicly advertised Aug 2026 as newbuilding resale: approx. 65m, 90T bollard pull, DP2 and FiFi-1 readiness. Availability requires AVE verification.",source:"Sher Worldwide"},
{id:"AVE-R006",title:"Deepwater PSV Requirement — Nigeria",type:"Platform Supply Vessel",market:"Offshore Nigeria",status:"Buyer requirement",price:"Commercial terms on qualification",currency:"USD",commercial:"Charter Requirement",img:"https://images.unsplash.com/photo-1518465058-68b098b6b6d3?auto=format&fit=crop&w=1200&q=80",note:"Public market requirement category: DP-capable PSVs support Nigerian deepwater fields. This is market intelligence, not an AVE-held mandate.",source:"West Africa Vessel Charter"}
]
const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const supabase=url&&key?createClient(url,key):null;
function Logo(){return <div className="brand"><span className="mark">A<span>V</span>E</span><span className="brandwords">AFRICAN<br/>VESSEL<br/>EXCHANGE</span></div>}
export default function Home(){
 const[q,setQ]=useState("");const[mode,setMode]=useState("All");const[modal,setModal]=useState(null);const[sent,setSent]=useState(false);const[sending,setSending]=useState(false);const[error,setError]=useState("");
 const rows=useMemo(()=>seed.filter(x=>(mode==="All"||x.status===mode)&&JSON.stringify(x).toLowerCase().includes(q.toLowerCase())),[q,mode]);
 async function submit(e){e.preventDefault();setSending(true);setError("");const d=Object.fromEntries(new FormData(e.currentTarget));if(!supabase){setError("AVE connection is temporarily unavailable.");setSending(false);return}const payload={name:d.name,company:d.company||null,email:d.email,phone:d.phone||null,intent:d.intent,details:d.details,opportunity:d.opportunity,source:"website"};for(const table of["inquiries","enquiries","leads"]){const{error}=await supabase.from(table).insert(payload);if(!error){setSent(true);setSending(false);return}}setError("We couldn't submit this yet. Please try again shortly.");setSending(false)}
 return <><header><a href="#" aria-label="African Vessel Exchange home"><Logo/></a><nav><a href="#market">Vessels</a><a href="#market">Charter</a><a href="#sell">Sell</a><a href="#capital">Capital</a><a href="#how">How it works</a><a href="#about">About</a></nav><div className="headBtns"><button className="plain" onClick={()=>setModal("signin")}>Sign in</button><button className="gold" onClick={()=>setModal("list")}>List a vessel →</button></div></header>
 <main><section className="hero"><div className="shade"></div><div className="heroText"><p className="eyebrow">AFRICA'S MARITIME MARKETPLACE</p><h1>Vessels.<br/>Capital.<br/><em>Opportunity.</em></h1><p className="lead">Buy, sell, charter and finance vessels across Africa and beyond. AVE connects ship owners, charterers, investors and maritime professionals for real opportunities and real transactions.</p><div className="buttons"><a className="gold button" href="#market">Browse vessels →</a><button className="outline" onClick={()=>setModal("list")}>List a vessel →</button></div><div className="trust"><span>♢ Verified workflow</span><span>◇ Secure enquiries</span><span>₦/$ NGN & USD</span><span>◎ Pan-African reach</span></div></div><div className="heroSide"><p>CONNECTING AFRICA TO GLOBAL MARITIME OPPORTUNITY</p><b>01 <span>Trade</span></b><b>02 <span>Charter</span></b><b>03 <span>Finance</span></b></div></section>
 <section className="finder" id="market"><div className="tabs">{["All","Public listing","Buyer requirement"].map(x=><button key={x} className={mode===x?"active":""} onClick={()=>setMode(x)}>{x==="All"?"Find a vessel":x}</button>)}</div><div className="search"><label>VESSEL / KEYWORD<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Type, location or keyword"/></label><label>REGION<select><option>Any African market</option><option>Nigeria</option><option>West Africa</option><option>Southern Africa</option><option>East Africa</option></select></label><button>Search vessels →</button></div></section>
 <section className="proof"><div><b>NGN + USD</b><span>Transaction currencies</span></div><div><b>Pan-African</b><span>Market coverage</span></div><div><b>Verified</b><span>Owner & broker workflow</span></div><div><b>Deal support</b><span>Qualified introductions</span></div></section>
 <section className="market"><div className="title"><div><p className="eyebrow dark">THE EXCHANGE</p><h2>Featured opportunities</h2><p>Qualified maritime opportunities, clearly labelled by verification status.</p></div><span>{rows.length} opportunities</span></div><div className="grid">{rows.map(x=><article className="card" key={x.id}><div className="art" style={{backgroundImage:`linear-gradient(180deg,transparent,#031725aa),url("${x.img}")`}}><span>{x.status.toUpperCase()}</span><strong>{x.type}</strong></div><div className="body"><small>{x.id} · {x.market}</small><h3>{x.title}</h3><dl><div><dt>PRICE / BUDGET</dt><dd>{x.price}</dd></div><div><dt>CURRENCY</dt><dd>{x.currency}</dd></div></dl><p className="note">{x.note}<br/><b>Source: {x.source}</b>{x.sourceUrl&&<> · <a href={x.sourceUrl} target="_blank" rel="noreferrer">View source ↗</a></>}</p><button className="green" onClick={()=>setModal(x.id)}>View & enquire →</button></div></article>)}</div></section>
 <section className="split" id="sell"><div className="photo owner"></div><div className="splitCopy"><p className="eyebrow">FOR VESSEL OWNERS</p><h2>Put your vessel in front of serious African demand.</h2><p>Submit sale or charter opportunities for qualification. AVE can present verified listings to buyers, charterers and capital partners without turning the platform into an unvetted classifieds board.</p><button className="gold" onClick={()=>setModal("list")}>List a vessel →</button></div></section>
 <section className="process" id="how"><p className="eyebrow">BUILT FOR REAL TRANSACTIONS</p><h2>From discovery to deal room.</h2><div className="steps">{[["01","Discover","Search sale, charter and finance opportunities."],["02","Qualify","Understand verification status before progressing."],["03","Connect","Submit requirements and reach the transaction desk."],["04","Transact","Progress diligence, offers and completion."]].map(s=><article key={s[0]}><b>{s[0]}</b><h3>{s[1]}</h3><p>{s[2]}</p></article>)}</div></section>
 <section className="capital" id="capital"><div><p className="eyebrow">CAPITAL & PARTNERSHIPS</p><h2>Marine assets meet capital.</h2><p>Owners can register financing requirements while investors, lenders and strategic buyers submit acquisition criteria.</p></div><button className="gold" onClick={()=>setModal("capital")}>Register capital interest →</button></section>
 <section className="about" id="about"><Logo/><div><p className="eyebrow dark">PEOPLE · VESSELS · CAPITAL</p><h2>A stronger maritime marketplace for Africa.</h2><p>Starting with Nigeria and built to connect credible marine opportunities across African markets and global counterparties.</p></div></section></main>
 <footer><Logo/><p>Buy · Sell · Charter · Finance</p><small>© 2026 African Vessel Exchange. Opportunity information must be independently verified before transaction.</small></footer>
 {modal&&<div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&(setModal(null),setSent(false),setError(""))}><div className="modal"><button className="x" onClick={()=>{setModal(null);setSent(false);setError("")}}>×</button>{sent?<><p className="eyebrow dark">AVE TRANSACTION DESK</p><h2>Received.</h2><p>Your submission has been securely recorded for qualification.</p></>:<><p className="eyebrow dark">AVE TRANSACTION DESK</p><h2>{modal==="list"?"List a vessel":modal==="capital"?"Register capital interest":modal==="signin"?"Account access":"Opportunity enquiry"}</h2><p>{modal==="signin"?"Secure member authentication is being prepared.":"Tell us enough to qualify the opportunity before an introduction."}</p>{modal!=="signin"&&<form onSubmit={submit}><input name="name" required placeholder="Full name"/><input name="company" placeholder="Company"/><input name="email" type="email" required placeholder="Business email"/><input name="phone" placeholder="Phone / WhatsApp"/><select name="intent" defaultValue={modal==="list"?"Sell a vessel":modal==="capital"?"Invest / provide capital":"Buy / charter"}><option>Buy / charter</option><option>Sell a vessel</option><option>Seek finance</option><option>Invest / provide capital</option></select><textarea name="details" required placeholder="Vessel, location, budget / asking price (USD / NGN) and timing"></textarea><input type="hidden" name="opportunity" value={modal}/>{error&&<p className="note">{error}</p>}<button className="green" disabled={sending}>{sending?"Submitting…":"Submit to AVE →"}</button></form>}</>}</div></div>}</>
}