"use client";
import {useMemo,useState} from "react";
import {createClient} from "@supabase/supabase-js";

const seed=[
{id:"AVE-L001",title:"DP2 AHTS — 200T Bollard Pull",type:"AHTS",market:"West Africa",status:"Public listing",price:"Price on request",currency:"USD",commercial:"For Sale",specs:"2012 · 74.5m · 16,000 BHP · 2,542T DWT",note:"Publicly advertised 2 Apr 2026. ABS class. AVE has not yet verified current availability or seller authority.",source:"Sher Worldwide",sourceUrl:"https://sher-worldwide.com/product/3317-2012-built-16000bhp-dp2-aht-supply-vessel/",img:"https://images.marinelink.com/images/maritime/skandi-atlantic-167084.jpg"},
{id:"AVE-L002",title:"AHTS — 204T Bollard Pull",type:"AHTS",market:"International / Africa enquiry",status:"Public listing",price:"Price on request",currency:"USD",commercial:"For Sale",specs:"76m · 12,000 BHP · 1,857T DWT · FiFi 1",note:"Publicly advertised 8 May 2026. IACS class. Location and availability require AVE verification.",source:"Sher Worldwide",sourceUrl:"https://sher-worldwide.com/product/3380-high-power-ahts-204t-bollard-pull-vessel-sale/",img:"https://cdn.offshorewind.biz/wp-content/uploads/sites/6/2018/04/05055613/far-scout.jpg"},
{id:"AVE-L003",title:"DP2 AHTS Newbuilding — 90T BP",type:"AHTS / Newbuild",market:"Asia / Africa deployment",status:"Public listing",price:"Price on request",currency:"USD",commercial:"For Sale",specs:"65m · DP2 · 90T BP · FiFi-1 ready",note:"Publicly advertised 5 Aug 2026 as a newbuilding resale. AVE has not verified current availability.",source:"Sher Worldwide",sourceUrl:"https://sher-worldwide.com/product/3799-65m-ahts-dp2-vessel-for-sale-china-resale/",img:"https://images.marinelink.com/images/maritime/skandi-atlantic-167084.jpg"},
{id:"AVE-L004",title:"2 × Multipurpose AHTS / OSV Newbuildings",type:"AHTS / OSV",market:"China / Global delivery",status:"Public listing",price:"Price on request",currency:"USD",commercial:"For Sale",specs:"66m · 13,000 HP · 160T BP · ~25 POB",note:"Publicly advertised 16 Sep 2026. Two vessels under construction. Progress and availability require AVE verification.",source:"Sher Worldwide",sourceUrl:"https://sher-worldwide.com/product/3948-13000hp-multipurpose-ahts-osv-newbuilding-transfer/",img:"https://cdn.offshorewind.biz/wp-content/uploads/sites/6/2018/04/05055613/far-scout.jpg"},
{id:"AVE-L005",title:"12,000 HP AHTS — 140T BP",type:"AHTS",market:"International / Africa enquiry",status:"Public listing",price:"Price on request",currency:"USD",commercial:"For Sale",specs:"2010 · 70m · 500m² deck · 2,040 DWT · DP1",note:"Publicly advertised 15 Sep 2026. Location and availability require AVE verification.",source:"VED Shipping",sourceUrl:"https://vedshipping.com/sale-and-purchase/vessels/ahtahtsahtsv/",img:"https://images.marinelink.com/images/maritime/skandi-atlantic-167084.jpg"},
{id:"AVE-L006",title:"Modern DP2 PSV — Sale / Charter",type:"Platform Supply Vessel",market:"International / Africa enquiry",status:"Public listing",price:"Price on request",currency:"USD",commercial:"Sale / Charter",specs:"2010 · 80m · 568m² deck · 1,500T deck load · 40 POB",note:"Publicly advertised 20 Sep 2026. Diesel-electric propulsion. Location and availability require AVE verification.",source:"VED Shipping",sourceUrl:"https://vedshipping.com/sale-and-purchase/vessels/offshore/",img:"https://medialibrary.damen.com/transform/9f05a654-a361-4018-8c9e-052010cbec6c/20161109-PSV-5000-PAUL-A-SACUTA-YN552041_030-jpg?io=transform%3Afill%2Cwidth%3A1200&quality=75"},
{id:"AVE-L007",title:"Newbuild Utility AHTS — 65T BP",type:"Utility AHTS",market:"International / Africa enquiry",status:"Public listing",price:"Price on request",currency:"USD",commercial:"For Sale",specs:"2025 · 42m · 4,400 BHP · FiFi-1 · 100T deck load",note:"Publicly advertised 12 Sep 2026. Unrestricted navigation. Availability requires AVE verification.",source:"VED Shipping",sourceUrl:"https://www.vedshipping.com/sale-and-purchase/vessels/ahtahtsahtsv/",img:"https://cdn.offshorewind.biz/wp-content/uploads/sites/6/2018/04/05055613/far-scout.jpg"},
{id:"AVE-L008",title:"AHT + AHTS Offshore Vessel Package",type:"AHT / AHTS",market:"UAE / Africa deployment",status:"Public listing",price:"Price on request",currency:"USD",commercial:"For Sale",specs:"2 vessels · ~75–80T BP · offshore support",note:"Publicly advertised 26 Jul 2026. Towing, anchor handling and supply support package. Availability requires AVE verification.",source:"Sher Worldwide",sourceUrl:"https://sher-worldwide.com/product/3728-aht-ahts-offshore-vessel-package-sale/",img:"https://images.marinelink.com/images/maritime/skandi-atlantic-167084.jpg"},
{id:"AVE-R009",title:"DP2 PSV — 1,000–1,200m² Deck Required",type:"Platform Supply Vessel",market:"Open requirement",status:"Buyer requirement",price:"Buyer enquiry",currency:"USD",commercial:"Purchase Requirement",specs:"2020+ build · DP2 · 1,000–1,200m² deck",note:"Public purchase request created 8 Sep 2026. AVE is not the mandate holder; requirement must be reconfirmed before nomination.",source:"ShipSelector",sourceUrl:"https://shipselector.com/requests/offshore-vessels",img:"https://enernav.mx/src/img/home/peregrina-thumb.jpg?v=2"},
{id:"AVE-L010",title:"DP2 AHTS — 115T BP Newbuild",type:"Multipurpose AHTS",market:"International / Africa enquiry",status:"Public listing",price:"Price on request",currency:"USD",commercial:"For Sale",specs:"2026 · 85.5m · 9,300 HP · 4,000T DWT · DP2",note:"Publicly advertised 2 Apr 2026 as a high-spec newbuild under construction. Availability requires AVE verification.",source:"Sher Worldwide",sourceUrl:"https://sher-worldwide.com/product/3319-115t-bollard-pull-dp2-multipurpose-ahts-2026/",img:"https://images.marinelink.com/images/maritime/skandi-atlantic-167084.jpg"}
];

const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const supabase=url&&key?createClient(url,key):null;
function Logo(){return <div className="brand"><span className="mark">A<span>V</span>E</span><span className="brandwords">AFRICAN<br/>VESSEL<br/>EXCHANGE</span></div>}

export default function Home(){
 const[q,setQ]=useState("");const[mode,setMode]=useState("All");const[region,setRegion]=useState("All");const[modal,setModal]=useState(null);const[sent,setSent]=useState(false);const[sending,setSending]=useState(false);const[error,setError]=useState("");
 const rows=useMemo(()=>seed.filter(x=>(mode==="All"||x.status===mode)&&(region==="All"||x.market.toLowerCase().includes(region.toLowerCase()))&&JSON.stringify(x).toLowerCase().includes(q.toLowerCase())),[q,mode,region]);
 async function submit(e){e.preventDefault();setSending(true);setError("");const d=Object.fromEntries(new FormData(e.currentTarget));if(!supabase){setError("AVE connection is temporarily unavailable.");setSending(false);return}const payload={submission_type:modal==="list"?"vessel_listing":modal==="requirement"?"vessel_requirement":modal==="capital"?"capital_interest":"opportunity_enquiry",full_name:d.name,company:d.company||null,email:d.email,phone:d.phone||null,intent:d.intent,opportunity_reference:modal&&modal.startsWith("AVE-")?modal:null,details:d.details,currency:"USD",status:"new"};const result=await supabase.from("intake_submissions").insert(payload);if(!result.error){setSent(true);setSending(false);return}setError("Submission failed. Please try again.");setSending(false)}
 return <><header><a href="#" aria-label="African Vessel Exchange home"><Logo/></a><nav><a href="#market">Vessels</a><a href="#market">Charter</a><a href="#sell">Sell</a><a href="#capital">Capital</a><a href="#how">How it works</a><a href="#about">About</a></nav><div className="headBtns"><button className="plain" onClick={()=>setModal("signin")}>Sign in</button><button className="plain" onClick={()=>setModal("requirement")}>Post requirement</button><button className="gold" onClick={()=>setModal("list")}>List a vessel →</button></div></header>
 <main><section className="hero"><div className="shade"></div><div className="heroText"><p className="eyebrow">AFRICA'S MARITIME MARKETPLACE</p><h1>Vessels.<br/>Capital.<br/><em>Opportunity.</em></h1><p className="lead">A specialist exchange for commercial vessels, charter requirements and maritime capital across Africa and connected global markets.</p><div className="buttons"><a className="gold button" href="#market">Browse vessels →</a><button className="outline" onClick={()=>setModal("requirement")}>Post a requirement →</button></div><div className="trust"><span>♢ Verification-led</span><span>◇ Qualified enquiries</span><span>₦/$ NGN & USD</span><span>◎ Pan-African reach</span></div></div><div className="heroSide"><p>CONNECTING AFRICA TO GLOBAL MARITIME OPPORTUNITY</p><b>01 <span>Trade</span></b><b>02 <span>Charter</span></b><b>03 <span>Finance</span></b></div></section>
 <section className="finder" id="market"><div className="tabs">{["All","Public listing","Buyer requirement"].map(x=><button key={x} className={mode===x?"active":""} onClick={()=>setMode(x)}>{x==="All"?"All opportunities":x}</button>)}</div><div className="search"><label>VESSEL / KEYWORD<input value={q} onChange={e=>setQ(e.target.value)} placeholder="AHTS, PSV, tug, DP2..."/></label><label>MARKET<select value={region} onChange={e=>setRegion(e.target.value)}><option value="All">Any market</option><option>Nigeria</option><option>West Africa</option><option>Africa</option></select></label><button>Search exchange →</button></div></section>
 <section className="proof"><div><b>{seed.filter(x=>x.status==="Public listing").length}</b><span>Sourced public listings</span></div><div><b>{seed.filter(x=>x.status==="Buyer requirement").length}</b><span>Published requirements</span></div><div><b>NGN + USD</b><span>Transaction currencies</span></div><div><b>Source-led</b><span>Every public lead attributable</span></div></section>
 <section className="market"><div className="title"><div><p className="eyebrow dark">LIVE MARKET INTELLIGENCE</p><h2>Vessels & requirements</h2><p>Public opportunities are sourced and clearly separated from future AVE-verified mandates.</p></div><span>{rows.length} shown</span></div><div className="grid">{rows.map(x=><article className="card" key={x.id}><div className="art" className="art" style={{backgroundImage:`linear-gradient(180deg,transparent,#031725d9),url("${x.img}")`}}><span className={x.status==="Buyer requirement"?"req":""}>{x.status.toUpperCase()}</span><strong>{x.type}</strong></div><div className="body"><small>{x.id} · {x.market}</small><h3>{x.title}</h3><p className="specs">{x.specs}</p><dl><div><dt>COMMERCIAL</dt><dd>{x.commercial}</dd></div><div><dt>PRICE / RATE</dt><dd>{x.price}</dd></div></dl><p className="note">{x.note}<br/><b>Source: </b><a href={x.sourceUrl} target="_blank" rel="noreferrer">{x.source} ↗</a></p><button className="green" onClick={()=>setModal(x.id)}>Enquire through AVE →</button></div></article>)}</div></section>
 <section className="inventoryGate"><div><p className="eyebrow">PRIVATE MARKET INVENTORY</p><h2>100+ sourced vessel opportunities.</h2><p>AVE is building a deeper transaction inventory across offshore support, tugs, barges, dredging, workboats and specialist tonnage. Public cards are a preview; member access unlocks the wider opportunity set.</p></div><div className="inventoryCount"><strong>100+</strong><span>market opportunities</span><button className="gold" onClick={()=>setModal("signin")}>View more opportunities →</button></div></section><section className="opportunityBand"><div><p className="eyebrow">CAN’T FIND THE RIGHT TONNAGE?</p><h2>Tell the market what you need.</h2><p>Post a vessel requirement for purchase or charter. AVE can structure the brief, identify matching tonnage and qualify potential owners or brokers.</p></div><button className="gold" onClick={()=>setModal("requirement")}>Post a vessel requirement →</button></section><section className="split" id="sell"><div className="photo owner"></div><div className="splitCopy"><p className="eyebrow">FOR OWNERS & BROKERS</p><h2>Bring credible tonnage to African demand.</h2><p>Submit a vessel for sale or charter. AVE qualifies the opportunity, records authority and availability, and separates verified inventory from public market intelligence.</p><button className="gold" onClick={()=>setModal("list")}>List a vessel →</button></div></section>
 <section className="premiumStrip"><div><b>01</b><span>Source</span><small>Commercial opportunities</small></div><div><b>02</b><span>Verify</span><small>Authority & availability</small></div><div><b>03</b><span>Structure</span><small>Capital & transaction</small></div><div><b>04</b><span>Close</span><small>Deal execution</small></div></section><section className="process" id="how"><p className="eyebrow">A TRANSACTION EXCHANGE, NOT A CLASSIFIEDS BOARD</p><h2>From discovery to deal room.</h2><div className="steps">{[["01","Discover","Search sourced vessel opportunities and requirements."],["02","Verify","Confirm authority, availability and commercial information."],["03","Qualify","Capture buyer, charterer or capital requirements."],["04","Transact","Progress introductions, diligence, offers and completion."]].map(s=><article key={s[0]}><b>{s[0]}</b><h3>{s[1]}</h3><p>{s[2]}</p></article>)}</div></section>
 <section className="capital" id="capital"><div><p className="eyebrow">CAPITAL & PARTNERSHIPS</p><h2>Marine assets meet capital.</h2><p>Owners can register financing requirements while investors, lenders and strategic buyers submit acquisition criteria.</p></div><button className="gold" onClick={()=>setModal("capital")}>Register capital interest →</button></section>
 <section className="partners"><div className="partnerHead"><p className="eyebrow dark">STRATEGIC PARTNERS</p><h2>Specialist capability around every transaction.</h2><p>AVE works with approved partners across capital, origination and African market execution.</p></div><div className="partnerGrid"><article className="partnerCard baa"><div className="baaMark"><b>B&amp;A</b><strong>Bankole &amp; Associates</strong><small>CAPITAL. PARTNERSHIPS. IMPACT.</small></div><span>Investment &amp; Advisory Partner</span><p>Transaction strategy, capital introductions and commercial advisory.</p></article><article className="partnerCard seventh"><a href="https://seventhspring.com.ng/" target="_blank" rel="noreferrer" aria-label="Visit Seventh Spring"><img className="partnerLogo" src="/partners/seventh-spring.svg" alt="Seventh Spring" /></a><span>Industrial &amp; Origination Partner</span><p>Opportunity origination, industrial relationships and African market access.</p></article></div></section><section className="about" id="about"><Logo/><div><p className="eyebrow dark">PEOPLE · VESSELS · CAPITAL</p><h2>A stronger maritime marketplace for Africa.</h2><p>AVE is being built from Nigeria to connect credible marine opportunities across African markets and global counterparties.</p></div></section></main>
 <footer><Logo/><p>Buy · Sell · Charter · Finance</p><small>© 2026 African Vessel Exchange. Public listings are market intelligence until independently verified by AVE.</small></footer>
 {modal&&<div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&(setModal(null),setSent(false),setError(""))}><div className="modal"><button className="x" onClick={()=>{setModal(null);setSent(false);setError("")}}>×</button>{sent?<><p className="eyebrow dark">AVE TRANSACTION DESK</p><h2>Received.</h2><p>Your submission has been recorded for qualification.</p></>:<><p className="eyebrow dark">AVE TRANSACTION DESK</p><h2>{modal==="list"?"List a vessel":modal==="requirement"?"Post a vessel requirement":modal==="capital"?"Register capital interest":modal==="signin"?"Account access":"Opportunity enquiry"}</h2><p>{modal==="signin"?"Secure member authentication is being prepared.":"Tell us enough to qualify the opportunity before an introduction."}</p>{modal!=="signin"&&<form onSubmit={submit}><input name="name" required placeholder="Full name"/><input name="company" placeholder="Company"/><input name="email" type="email" required placeholder="Business email"/><input name="phone" placeholder="Phone / WhatsApp"/><select name="intent" defaultValue={modal==="list"?"Sell a vessel":modal==="requirement"?"Post vessel requirement":modal==="capital"?"Invest / provide capital":"Buy / charter"}><option>Buy / charter</option><option>Post vessel requirement</option><option>Sell a vessel</option><option>Seek finance</option><option>Invest / provide capital</option></select><textarea name="details" required placeholder={modal==="requirement"?"Required vessel type, specs, location, charter/purchase, budget and required date":"Vessel, location, budget / asking price and timing"}></textarea><input type="hidden" name="opportunity" value={modal}/>{error&&<p className="note">{error}</p>}<button className="green" disabled={sending}>{sending?"Submitting…":"Submit to AVE →"}</button></form>}</>}</div></div>}</>
}